-- delete tables id exists : 
-- make sur there isn't another table scheme registered.
drop table Sponsoring if exists;
drop table RacingTeam if exists;
drop table Sponsor if exists;
drop table Race if exists;
drop table Meeting if exists;
drop table Member if exists;
drop table Vehicule if exists;
drop table Messages if exists;
drop table ForumTopic if exists;
drop table VehiculeType if exists;
drop table Circuit if exists;


create table Circuit (
  idCircuit           integer generated by default as identity (start with 1, increment by 1) not null,
  place               varchar(50) not null,
  distance            float,
  turnNumber          integer,
  possibleSpectator   integer,
  primary key (idCircuit)
);

create table VehiculeType (
  idVehiculeType      integer generated by default as identity (start with 1, increment by 1) not null,
  Name                varchar(30) not null,
  WheelNumber         integer,
  maxSpeed            float,
  maxWeight           float,
  primary key (idVehiculeType)
);

create table ForumTopic (
  idForumTopic  integer generated by default as identity (start with 1, increment by 1) not null,
  title         varchar(50) not null,
  primary key (idForumTopic)
);

create table Messages (
  idMessage     integer generated by default as identity (start with 1, increment by 1) not null,
  content       varchar(1000) not null,
  topic         integer foreign key ForumTopic(idForumTopic),
  primary key (idMessage)
);

create table Vehicule (
  idVehicule        integer generated by default as identity (start with 1, increment by 1) not null,
  Branch            varchar(30) not null,
  Model             varchar(30) not null,
  LicensePlate      varchar(30) not null,
  FirstLicensePlate integer,
  primary key (idVehicule)
);

create table Member (
  idMember      integer generated by default as identity (start with 1, increment by 1) not null,
  Name          varchar(30) not null,
  FirstName     varchar(30) not null,
  email         varchar(100) not null,
  Vehicule      integer foreign key references Vehicule(idVehicule),
  subscriber    boolean,
  primary key (idMember)
);


create table Meeting (
  idMeeting       integer generated by default as identity (start with 1, increment by 1) not null,
  place           varchar(100) not null,
  date            date,
  title           varchar(100) not null,
  guests          integer foreign key references Member(idMember),
  primary key (idMeeting)
);


create table Race (
  idRace        integer generated by default as identity (start with 1, increment by 1) not null,
  idCircuit     integer foreign key references Circuit(idCircuit),
  date          date,
  VehiculeType  integer foreign key references VehiculeType(idVehiculeType),
  Participants  integer foreign key references Member(idMember),
  primary key (idRace)
);

create table Sponsor (
  idSponsor           integer generated by default as identity (start with 1, increment by 1) not null,
  investmentcapital   float,
  creationDate        date,
  primary key (idSponsor)
);

create table RacingTeam (
  idRacingTeam  integer generated by default as identity (start with 1, increment by 1) not null,
  Name          varchar(30) not null,
  Ranking       integer,
  Supporter     integer foreign key references Member(idMember),
  Sponsor       integer foreign key references Sponsor(idSponsor),
  primary key (idRacingTeam)
);

create table Sponsoring (
  idSponsoring      integer generated by default as identity (start with 1, increment by 1) not null,
  idRacingTeam      integer foreign key references RacingTeam(idRacingTeam),
  idSponsor         integer foreign key references Sponsor(idSponsor),
  startingDate      date,
  endingDate        date,
  investmentcapital float,
  primary key (idSponsoring)
);


commit;